Banktive.Web/Controllers/CreditController.cs
using Banktive.Web.Data;
using Banktive.Web.Models;
using Banktive.Web.Models.CreditModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class CreditController : Controller
    {

        private ApplicationDbContext _db;

        public CreditController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(long? wallet, int? month, int? year, int page = 1, int qty = 20)
        {
            IndexCreditViewModel model = new IndexCreditViewModel(_db, User.Identity.Name);
            IEnumerable<CreditDTO> checks = _db.Checks.Include(x => x.Wallet).Include(x => x.Currency).Where(x => x.UserId == User.Identity.Name && (x.CheckStatusId == Constants.CheckConfirmed || x.CheckStatusId == Constants.CheckCashed))
                .Select(x => new CreditDTO
                {
                    Amount = x.Amount,
                    AssetCode = x.Currency.Code,
                    Comments = x.Comments,
                    CreatedAt = x.CreatedAt,
                    DestinationAddress = x.Destination != null ? x.Destination.Account : x.XRPLDestinationWallet,
                    Id = x.Id,
                    Wallet = x.Wallet.Name,
                    WalletId = x.OriginWalletId,
                    OriginAddress = x.Wallet.Alias,
                    IsSend = true, DateToCash = x.DateToCash
                });
            var myWalletAddresses = _db.Wallets.Where(x => x.UserId == User.Identity.Name).Select(x => x.XRPLAddress);
            var filterTransferForWallets = _db.Checks.Where(x => myWalletAddresses.Any(y => y == x.XRPLDestinationWallet) && (x.CheckStatusId == Constants.CheckConfirmed || x.CheckStatusId == Constants.CheckCashed)).Select(x => new CreditDTO
            {
                Amount = x.Amount,
                AssetCode = x.Currency.Code,
                Comments = x.Comments,
                CreatedAt = x.CreatedAt,
                DestinationAddress = x.Destination.Account,
                Id = x.Id,
                Wallet = x.Wallet.Name,
                WalletId = x.OriginWalletId,
                OriginAddress = x.Wallet.Alias,
                IsSend = false,
                DateToCash = x.DateToCash
            });
            checks = checks.Concat(filterTransferForWallets);
            if (wallet.HasValue)
            {
                checks = checks.Where(x => x.WalletId == wallet.Value);
            }
            if (month.HasValue)
            {
                checks = checks.Where(x => x.CreatedAt.Month == month.Value);
            }
            if (year.HasValue)
            {
                checks = checks.Where(x => x.CreatedAt.Year == year.Value);
            }
            model.Checks = checks.OrderByDescending(x => x.CreatedAt).Skip(qty * (page - 1)).Take(qty);
            model.Form.Page = page;
            model.Form.Year = year;
            model.Form.Month = month;
            model.Form.WalletId = wallet;
            return View(model);
        }

        public IActionResult SelectWallet()
        {
            SelectWalletViewModel model = new SelectWalletViewModel(_db, User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public IActionResult EnableWallet(long id)
        {
            Wallet wallet = _db.Wallets.SingleOrDefault(x => x.Id == id);
            if (wallet == null || wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("SelectWallet");
            }
            CreditWallet creditWallet = _db.CreditWallets.SingleOrDefault(x => x.Id == id);
            if(creditWallet == null)
            {
                creditWallet = new CreditWallet()
                {
                    Id = id,
                    CreatedAt = DateTime.UtcNow,
                    Enabled = true,
                    UsedAmount = 0,
                    TotalAmount = 10000, UserId = User.Identity.Name
                };
                _db.CreditWallets.Add(creditWallet);
            }
            else
            {
                if(!creditWallet.Enabled)
                {
                    creditWallet.Enabled = true;
                }
                else
                {
                    if (creditWallet.UsedAmount == 0)
                    {
                        creditWallet.Enabled = false;
                    }
                }
            }
            _db.SaveChanges();
            return RedirectToAction("SelectWallet");
        }

        public IActionResult PayWithCheck(long? id)
        {
            PayWithCheckViewModel model = new PayWithCheckViewModel(_db, id, User.Identity.Name);
            if (model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("SelectWallet");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult PayWithCheck(PayWithCheckFormModel Form)
        {
            if(Form.Amount.HasValue)
            {
                CreditWallet creditWallet = _db.CreditWallets.SingleOrDefault(x => x.Id == Form.OriginWalletId);
                if((creditWallet.TotalAmount - creditWallet.UsedAmount) < Form.Amount.Value)
                {
                    ModelState.AddModelError("Form.Amount", "You do not have enough available balance for this transaction.");
                }
            }
            if(Form.DateToCash.HasValue)
            {
                if(Form.DateToCash.Value.Date <= DateTime.UtcNow.Date)
                {
                    ModelState.AddModelError("Form.DateToCash", "The date must be in the future (from tomorrow).");
                }
            }
            PayWithCheckViewModel model = new PayWithCheckViewModel(_db, Form.OriginWalletId, User.Identity.Name);
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }

            Destination destination = _db.Destinations.SingleOrDefault(x => x.Id == Form.DestinationId.Value);
            string XRPLDestination = destination.Account;
            Wallet existingWalletForDestination = _db.Wallets.FirstOrDefault(x => x.Alias == XRPLDestination || x.Id.ToString() == XRPLDestination);
            if (existingWalletForDestination != null)
            {
                XRPLDestination = existingWalletForDestination.XRPLAddress;
            }

            Check check = new Check
            {
                Id = Guid.NewGuid(), CreatedAt = DateTime.UtcNow, Amount = Form.Amount.Value,
                 OriginWalletId = Form.OriginWalletId, CheckStatusId = Constants.CheckCreated, Comments = Form.Comments,
                 CurrencyId = Constants.Currency_XRP, UserId = User.Identity.Name, DestinationId = Form.DestinationId,
                 XRPLDestinationWallet = XRPLDestination, DateToCash = Form.DateToCash.Value
            };
            _db.Checks.Add(check);
            _db.SaveChanges();
            return RedirectToAction("ConfirmCheck", new { id = check.Id });
        }

        public IActionResult ConfirmCheck(Guid id)
        {
            ConfirmCheckViewModel model = new ConfirmCheckViewModel(_db, id);
            if (model.Check == null || model.Check.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmCheck(ConfirmCheckFormModel Form)
        {
            ConfirmCheckViewModel model = new ConfirmCheckViewModel(_db, Form.Id);
            if (model.Check == null || model.Check.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            Check check = _db.Checks.Include(x => x.Currency).Include(x => x.Destination)
                .Include(x => x.CheckStatus).SingleOrDefault(x => x.Id == Form.Id);

            if (!string.IsNullOrEmpty(Form.Cancelled))
            {
                check.CheckStatusId = Constants.CheckCancelled;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }
            
            check.CheckStatusId = Constants.CheckConfirmed;
            check.CheckXRPLId = Form.CheckXRPLId;
            check.Fee = 0;

            CreditWallet creditWallet = _db.CreditWallets.SingleOrDefault(x => x.Id == check.OriginWalletId);
            creditWallet.UsedAmount += check.Amount;

            _db.SaveChanges();

            return RedirectToAction("ViewCheck", new { id = Form.Id });
        }

        public IActionResult ViewCheck(Guid id)
        {
            ViewCheckViewModel model = new ViewCheckViewModel(_db, id);
            //if (model.Check == null || model.Check.UserId != User.Identity.Name)
            //{
            //    return RedirectToAction("Index");
            //}
            return View(model);
        }

        [HttpPost]
        public IActionResult CashCheck(Guid id)
        {
            Check check = _db.Checks.SingleOrDefault(x => x.Id ==id);
            check.DateToCash = DateTime.UtcNow;
            check.CheckStatusId = Constants.CheckCashed;

            Payment payment = new Payment
            {
                Amount = check.Amount,
                Comments = check.Comments,
                PaymentStatusId = Constants.PaymentConfirmed,
                PaymentTypeId = Constants.CheckPayment,
                CreatedAt = DateTime.UtcNow,
                CurrencyId = Constants.Currency_XRP,
                DestinationId = check.DestinationId,
                XRPLDestinationWallet = check.XRPLDestinationWallet,
                Id = Guid.NewGuid(),

Banktive.Web/Controllers/WalletController.cs
using Banktive.Web.Data;
using Banktive.Web.Models.WalletModel;
using Banktive.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class WalletController : Controller
    {
        private ApplicationDbContext _db;
        private XRPLService _XRPLService;

        public WalletController(ApplicationDbContext db, XRPLService xrplService)
        {
            _db = db;
            _XRPLService = xrplService;
        }

        public IActionResult Index()
        {
            IndexWalletViewModel model = new IndexWalletViewModel(_db, User.Identity.Name);
            if(model.Profile == null)
            {
                return RedirectToAction("Index", "Setting");
            }
            return View(model);
        }

        public IActionResult Create()
        {
            CreateWalletViewModel model = new CreateWalletViewModel(_db);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateWalletFormModel Form)
        {
            CreateWalletViewModel model = new CreateWalletViewModel(_db);
            if (!string.IsNullOrWhiteSpace(Form.Alias))
            {
                string alias = Form.Alias.ToLower();
                bool existAlias = _db.Wallets.Any(x => x.Alias == alias);
                if (existAlias)
                {
                    ModelState.AddModelError("Form.Alias", "The alias is already occupied by another account");
                }
            }
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }

            Wallet wallet = new Wallet
            {
                 Alias = Form.Alias, CreatedAt = DateTime.UtcNow, CurrencyId = Form.CurrencyId.Value,
                 XRPLAddress = Form.XRPLAddress, Description = Form.Description, Name = Form.Name,
                 XRPLSeed = Form.XRPLSeed, UserId = User.Identity.Name
            };
            _db.Wallets.Add(wallet);
            _db.SaveChanges();
            return RedirectToAction("View", new { id = wallet.Id });
        }

        public IActionResult View(long id)
        {
            ViewWalletViewModel model = new ViewWalletViewModel(_db, id);
            if(model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Update(long id)
        {
            UpdateWalletViewModel model = new UpdateWalletViewModel(_db, id);
            if (model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(UpdateWalletFormModel Form)
        {
            UpdateWalletViewModel model = new UpdateWalletViewModel(_db, Form.Id);
            if (model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                model.Form = Form;
                return View(model);
            }
            Wallet wallet = _db.Wallets.SingleOrDefault(x => x.Id == Form.Id);
            wallet.Name = Form.Name;
            wallet.Description = Form.Description;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetNativeBalance(long id)
        {
            Wallet wallet = _db.Wallets.SingleOrDefault(x => x.Id == id);
            if (wallet== null || wallet.UserId != User.Identity.Name)
            {
                return Json(null);
            }
            var nativeBalance = await _XRPLService.GetNativeBalance("wss://s.altnet.rippletest.net:51233", wallet.XRPLAddress);
            if (nativeBalance == null)
            {
                return Json(null);
            }
            return Json(nativeBalance);
        }
    }
}

Banktive.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banktive</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Banktive.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banktive</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Setting" asp-action="Index">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wallet" asp-action="Index">Wallets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Payments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Destination" asp-action="Index">Destinations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Credit" asp-action="Index">Credits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deposit" asp-action="Index">Deposits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Services</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Banktive.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>