Banktive.Web/Models/CreditModel/SelectWalletViewModel.cs
using Banktive.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Models.CreditModel
{
    public class SelectWalletViewModel
    {
        public IEnumerable<Wallet> Wallets { get; set; }
        public IEnumerable<CreditWallet> CreditWallets { get; set; }

        public SelectWalletViewModel(ApplicationDbContext db, string? name)
        {
            Wallets = db.Wallets.Include(x => x.Currency).Where(x => x.UserId == name).OrderBy(x => x.Name);
            CreditWallets = db.CreditWallets.Where(x => x.UserId == name).ToList();
        }
    }
}

Banktive.Web/Models/DepositModel/ConfirmTimeDepositViewModel.cs
using Banktive.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Models.DepositModel
{
    public class ConfirmTimeDepositViewModel
    {
        public Deposit Deposit { get; set; }

        public ConfirmTimeDepositFormModel Form { get; set; }

        public ConfirmTimeDepositViewModel(ApplicationDbContext db, Guid id)
        {
            Deposit = db.Deposits.Include(x => x.Wallet).Include(x => x.Currency).Include(x => x.Destination).SingleOrDefault(x => x.Id == id);
            Form = new ConfirmTimeDepositFormModel { Id = id };
        }

    }
}

Banktive.Web/Models/DepositModel/CreateTimeDepositViewModel.cs
using Banktive.Web.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Banktive.Web.Models.DepositModel
{
    public class CreateTimeDepositViewModel
    {
        public Wallet Wallet { get; set; }
        public IEnumerable<SelectListItem> Destinations { get; set; }
        public CreateTimeDepositFormModel Form { get; set; }

        public CreateTimeDepositViewModel(ApplicationDbContext db, long? id, string? username)
        {
            Wallet = db.Wallets.SingleOrDefault(x => x.Id == id);
            Destinations = db.Destinations.Where(x => x.UserId == username).OrderBy(x => x.Name)
                .Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            Form = new CreateTimeDepositFormModel {  OriginWalletId = id };
        }
    }
}

Banktive.Web/Models/DepositModel/SelectWalletViewModel.cs
using Banktive.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Models.DepositModel
{
    public class SelectWalletViewModel
    {
        public IEnumerable<Wallet> Wallets { get; set; }

        public SelectWalletViewModel(ApplicationDbContext db, string? name)
        {
            Wallets = db.Wallets.Include(x => x.Currency).Where(x => x.UserId == name).OrderBy(x => x.Name);
        }
    }
}

Banktive.Web/Models/DepositModel/ViewTimeDepositViewModel.cs
using Banktive.Web.Data;
using Microsoft.EntityFrameworkCore;
namespace Banktive.Web.Models.DepositModel
{
    public class ViewTimeDepositViewModel
    {
        public Deposit Deposit { get; set; }
        public Wallet WalletForCash { get; set; }
        public ViewTimeDepositViewModel(ApplicationDbContext db, Guid id)
        {
            Deposit = db.Deposits.Include(x => x.Currency).Include(x => x.Destination).Include(x => x.Wallet)
                .Include(x => x.DepositStatus).SingleOrDefault(x => x.Id == id);

            WalletForCash = db.Wallets.SingleOrDefault(x => x.XRPLAddress == Deposit.XRPLDestinationWallet);
        }
    }
}

Banktive.Web/Models/PaymentModel/SelectWalletViewModel.cs
using Banktive.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Models.PaymentModel
{
    public class SelectWalletViewModel
    {
        public IEnumerable<Wallet> Wallets { get; set; }

        public SelectWalletViewModel(ApplicationDbContext db, string? name)
        {
            Wallets = db.Wallets.Include(x => x.Currency).Where(x => x.UserId == name).OrderBy(x => x.Name);
        }
    }
}

Banktive.Web/Controllers/DepositController.cs
using Banktive.Web.Data;
using Banktive.Web.Models;
using Banktive.Web.Models.DepositModel;
using Banktive.Web.Services;
using Banktive.Web.Services.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class DepositController : Controller
    {
        private ApplicationDbContext _db;
        private XRPLService _XRPLService;

        public DepositController(ApplicationDbContext db, XRPLService xrplService)
        {
            _db = db;
            _XRPLService = xrplService;
        }

        public IActionResult Index(long? wallet, int? month, int? year, int page = 1, int qty = 20)
        {
            IndexDepositViewModel model = new IndexDepositViewModel(_db, User.Identity.Name);
            IEnumerable<DepositDTO> deposits = _db.Deposits.Include(x => x.Wallet).Include(x => x.Currency).Where(x => x.UserId == User.Identity.Name && (x.DepositStatusId == Constants.EscrowConfirmed || x.DepositStatusId == Constants.EscrowCashed || x.DepositStatusId == Constants.EscrowExpired))
                .Select(x => new DepositDTO
                {
                    Amount = x.Amount,
                    AssetCode = x.Currency.Code,
                    Comments = x.Comments,
                    CreatedAt = x.CreatedAt,
                    DestinationAddress = x.Destination != null ? x.Destination.Account : x.XRPLDestinationWallet,
                    Id = x.Id,
                    Wallet = x.Wallet.Name,
                    WalletId = x.OriginWalletId,
                    OriginAddress = x.Wallet.Alias,
                    IsSend = true,
                    DateToCash = x.DateToCash
                });
            var myWalletAddresses = _db.Wallets.Where(x => x.UserId == User.Identity.Name).Select(x => x.XRPLAddress);
            var filterDepositsForWallets = _db.Deposits.Where(x => myWalletAddresses.Any(y => y == x.XRPLDestinationWallet) && (x.DepositStatusId == Constants.EscrowConfirmed || x.DepositStatusId == Constants.EscrowCashed || x.DepositStatusId == Constants.EscrowExpired)).Select(x => new DepositDTO
            {
                Amount = x.Amount,
                AssetCode = x.Currency.Code,
                Comments = x.Comments,
                CreatedAt = x.CreatedAt,
                DestinationAddress = x.Destination.Account,
                Id = x.Id,
                Wallet = x.Wallet.Name,
                WalletId = x.OriginWalletId,
                OriginAddress = x.Wallet.Alias,
                IsSend = false,
                DateToCash = x.DateToCash
            });
            deposits = deposits.Concat(filterDepositsForWallets);
            if (wallet.HasValue)
            {
                deposits = deposits.Where(x => x.WalletId == wallet.Value);
            }
            if (month.HasValue)
            {
                deposits = deposits.Where(x => x.CreatedAt.Month == month.Value);
            }
            if (year.HasValue)
            {
                deposits = deposits.Where(x => x.CreatedAt.Year == year.Value);
            }
            model.Deposits = deposits.OrderByDescending(x => x.CreatedAt).Skip(qty * (page - 1)).Take(qty);
            model.Form.Page = page;
            model.Form.Year = year;
            model.Form.Month = month;
            model.Form.WalletId = wallet;
            return View(model);
        }

        public IActionResult SelectWallet()
        {
            SelectWalletViewModel model = new SelectWalletViewModel(_db, User.Identity.Name);
            return View(model);
        }

        public IActionResult CreateTimeDeposit(long? id)
        {
            CreateTimeDepositViewModel model = new CreateTimeDepositViewModel(_db, id, User.Identity.Name);
            if (model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("SelectWallet");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult CreateTimeDeposit(CreateTimeDepositFormModel Form)
        {
            CreateTimeDepositViewModel model = new CreateTimeDepositViewModel(_db, Form.OriginWalletId, User.Identity.Name);
            if (Form.DateToCash.HasValue)
            {
                if (Form.DateToCash.Value.Date <= DateTime.UtcNow.Date)
                {
                    ModelState.AddModelError("Form.DateToCash", "The date must be in the future (from tomorrow).");
                }
            }
            if(!ModelState.IsValid)
            {
                
                model.Form = Form;
                return View(model);
            }

            Destination destination = _db.Destinations.SingleOrDefault(x => x.Id == Form.DestinationId.Value);
            string XRPLDestination = destination.Account;
            Wallet existingWalletForDestination = _db.Wallets.FirstOrDefault(x => x.Alias == XRPLDestination || x.Id.ToString() == XRPLDestination);
            if (existingWalletForDestination != null)
            {
                XRPLDestination = existingWalletForDestination.XRPLAddress;
            }

            Deposit deposit = new Deposit()
            {
                Id = Guid.NewGuid(), CreatedAt = DateTime.UtcNow, Amount = Form.Amount.Value,
                Comments = Form.Comments, CurrencyId = Constants.Currency_XRP, DateToCash = Form.DateToCash,
                DepositStatusId = Constants.EscrowCreated, DepositTypeId = Constants.TimeEscrow, DestinationId = Form.DestinationId,
                XRPLDestinationWallet = XRPLDestination, OriginWalletId = Form.OriginWalletId.Value, UserId = User.Identity.Name
            };
            _db.Deposits.Add(deposit);
            _db.SaveChanges();

            return RedirectToAction("ConfirmTimeDeposit", new { id = deposit.Id });
        }

        public IActionResult ConfirmTimeDeposit(Guid id)
        {
            ConfirmTimeDepositViewModel model = new ConfirmTimeDepositViewModel(_db, id);
            if (model.Deposit == null || model.Deposit.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmTimeDeposit(ConfirmTimeDepositFormModel Form)
        {
            ConfirmTimeDepositViewModel model = new ConfirmTimeDepositViewModel(_db, Form.Id);
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }

            Deposit deposit = _db.Deposits.SingleOrDefault(x => x.Id == Form.Id);

            if (!string.IsNullOrEmpty(Form.Cancelled))
            {
                deposit.DepositStatusId = Constants.EscrowCancelled;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            XRPLCreateEscrowResult resultDeposit = await _XRPLService.CreateEscrow("wss://s.altnet.rippletest.net:51233", deposit.XRPLDestinationWallet, deposit.Amount,
                deposit.Wallet.XRPLAddress, deposit.Wallet.XRPLSeed, deposit.DateToCash.Value);

            if (resultDeposit.Successful)
            {
                deposit.DepositStatusId = Constants.EscrowConfirmed;
                deposit.Fee = resultDeposit.FeeAmount;
                deposit.XRPLSequence = (int?)resultDeposit.Sequence;
                deposit.TransactionHash = resultDeposit.Hash;
            }
            else
            {
                deposit.DepositStatusId = Constants.EscrowRejected;
            }
            deposit.ConfirmationAt = DateTime.UtcNow;
            _db.SaveChanges();

            return RedirectToAction("ViewTimeDeposit", new { id = Form.Id });
        }

        public IActionResult ViewTimeDeposit(Guid id)
        {
            ViewTimeDepositViewModel model = new ViewTimeDepositViewModel(_db, id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CashTimeDeposit(Guid id, long idWalletToCash)
        {
            Deposit deposit = _db.Deposits.Include(x => x.Wallet).SingleOrDefault(x => x.Id == id);
            Wallet walletToCash = _db.Wallets.SingleOrDefault(x => x.Id == idWalletToCash);
            if (walletToCash == null || walletToCash.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }

            XRPLCreateEscrowResult resultDeposit = await _XRPLService.FinishEscrow("wss://s.altnet.rippletest.net:51233",
                walletToCash.XRPLAddress, walletToCash.XRPLSeed, deposit.Wallet.XRPLAddress, (uint)deposit.XRPLSequence.Value);
            if(resultDeposit != null && resultDeposit.Successful)
            {
                Payment payment = new Payment
                {
                    Amount = deposit.Amount,
                    Comments = deposit.Comments,
                    PaymentStatusId = Constants.PaymentConfirmed,
                    PaymentTypeId = Constants.TimeDepositPayment,
                    CreatedAt = DateTime.UtcNow,
                    CurrencyId = Constants.Currency_XRP,
                    DestinationId = deposit.DestinationId,
                    XRPLDestinationWallet = deposit.XRPLDestinationWallet,
                    Id = Guid.NewGuid(),
                    OriginWalletId = deposit.OriginWalletId,
                    UserId = deposit.UserId,
                    ConfirmationAt = DateTime.UtcNow,
                    Fee = resultDeposit.FeeAmount
                };
                _db.Payments.Add(payment);

                deposit.DepositStatusId = Constants.EscrowCashed;
            }

            
            _db.SaveChanges();
            return RedirectToAction("ViewTimeDeposit", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> CancelTimeDeposit(Guid id)
        {

Banktive.Web/Views/Deposit/ConfirmTimeDeposit.cshtml
@model Banktive.Web.Models.DepositModel.ConfirmTimeDepositViewModel
@{
    ViewData["Title"] = "Approve deposit";
}

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Form.Id)
    <div class="row">
        <div class="col-md-6">
            <h3>Details of payment</h3>
            Wallet: <b>@Model.Deposit.Wallet.Name</b> <br />
            Amount: <b>@Model.Deposit.Amount</b> <br />
            Date to cash: <b>@Model.Deposit.DateToCash.Value.ToLocalTime()</b> <br />
            Currency: <b>@Model.Deposit.Currency.Name (@Model.Deposit.Currency.Code)</b> <br />
        </div>
        <div class="col-md-6">
            <br />
            Destination: <b>@(Model.Deposit.Destination != null? Model.Deposit.Destination.Name + " ("+Model.Deposit.XRPLDestinationWallet+")":Model.Deposit.XRPLDestinationWallet) </b> <br />
            Creation date: <b>@Model.Deposit.CreatedAt.ToLocalTime()</b> <br />
            Comments: <b>@Model.Deposit.Comments</b> <br />
        </div>
    </div>


    <div class="row">
        <div class="col-md-3">
            <br />
        </div>
        <div class="form-group col-md-5">
            <input type="submit" value="Cancel" class="btn btn-warning loadingButton" name="Form.Cancelled" /> &emsp;
            <input type="submit" class="btn btn-primary loadingButton" value="Approve payment" />
        </div>
    </div>
}

Banktive.Web/Views/Deposit/CreateTimeDeposit.cshtml
@model Banktive.Web.Models.DepositModel.CreateTimeDepositViewModel
@{
    ViewData["Title"] = "Enter the data for time held deposit";
}

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />



@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Form.OriginWalletId)
    <div class="row mt-2">
        <div class="col-md-2">
            Destination:
        </div>
        <div class="col-md-6">
            @Html.DropDownListFor(x => x.Form.DestinationId, Model.Destinations, "Select destination", new { @class = "form-control" }) <br />
            @Html.ValidationMessageFor(x => x.Form.DestinationId)
        </div>
        <div class="col-md-3">
            <div class="alert alert-success" role="alert">
                Select the recipient for your deposit
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-2">
            Amount:
        </div>
        <div class="col-md-6">
            @Html.TextBoxFor(x => x.Form.Amount, new { @class = "form-control", type="number" }) <br />
            @Html.ValidationMessageFor(x => x.Form.Amount)
        </div>
        <div class="col-md-3">
            <div class="alert alert-success" role="alert">
                Enter the amount to send
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-2">
            Date to cash:
        </div>
        <div class="col-md-6">
            @Html.TextBoxFor(x => x.Form.DateToCash, new { @class = "form-control", type="date" }) <br />
            @Html.ValidationMessageFor(x => x.Form.DateToCash)
        </div>
        <div class="col-md-3">
            <div class="alert alert-success" role="alert">
                Enter the date the deposit will be released in order to be cashed.
            </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-2">
            Comments (optional):
        </div>
        <div class="col-md-6">
            @Html.TextBoxFor(x => x.Form.Comments, new { @class = "form-control" }) <br />
            @Html.ValidationMessageFor(x => x.Form.Comments)
        </div>
        <div class="col-md-3">
            <div class="alert alert-success" role="alert">
                If you have any comments, enter them here.
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <br />
        </div>
        <div class="form-group col-md-5">
            <input type="submit" class="btn btn-primary loadingButton" value="Send" /> &emsp; <a href="@Url.Action("SelectWallet","Deposit")" class="btn btn-warning loadingButton">Back</a>
        </div>
    </div>
}

Banktive.Web/Views/Deposit/Index.cshtml
@model Banktive.Web.Models.DepositModel.IndexDepositViewModel
@{
    ViewData["Title"] = "My deposits";
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        @Html.ActionLink("Make time held deposit", "SelectWallet","Deposit",null,new {@class="btn btn-info"})
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />


<div class="row">
    <div class="col-12">
        @using (Html.BeginForm(null, null, FormMethod.Get))
        {
        <div class="row">
            <div class="col-md-3">
                Wallet:@Html.DropDownListFor(x => x.Form.WalletId, Model.Wallets, "Select a wallet", new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                Year: @Html.DropDownListFor(x => x.Form.Year, Model.Years, "Select a year", new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                Month: @Html.DropDownListFor(x => x.Form.Month, Model.Months, "Select a month", new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                <br />
                <input type="submit" value="Filter" class="btn btn-secondary loadingButton" />
            </div>
        </div>
        }
    </div>
            

    </div>
<br /><br />
@if (Model.Deposits.Any())
{
    <div class="row">
        <div class="col-6 text-right">
            @if (Model.Page > 1)
            {
                <a href="@Url.Action("Index","Deposit",new { page = (Model.Form.Page - 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Previous</a>
            }
        </div>
        <div class="col-6 text-left">
            <a href="@Url.Action("Index","Deposit",new { page = (Model.Form.Page + 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Next</a>
        </div>
    </div>
    <table class="table table-responsive">
        <thead>
            <tr>
                <th>Date</th>
                <th>Wallet</th>
                <th>Destination</th>
                <th>Amount (currency)</th>
                <th>Time to Cash</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var payment in Model.Deposits)
            {
                <tr class="@(payment.IsSend? "table-warning":"table-success")">
                    <td>@payment.CreatedAt.ToLocalTime()</td>
                    <td>@payment.OriginAddress</td>
                    <td>@payment.DestinationAddress</td>
                    <td>
                        @payment.Amount (@payment.AssetCode)
                    </td>
                    <td>
                        @(payment.DateToCash.HasValue? payment.DateToCash.Value.ToLocalTime() : "")
                    </td>
                    <td>@Html.ActionLink("Details", "ViewTimeDeposit", "Deposit", new { id = payment.Id }, new { @class = "btn btn-success loadingButton" })</td>
                </tr>
            }
        </tbody>
    </table>
    <div class="row">
        <div class="col-6 text-right">
            @if (Model.Page > 1)
            {
                <a href="@Url.Action("Index","Deposit",new { page = (Model.Form.Page - 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Previous</a>
            }
        </div>
        <div class="col-6 text-left">
            <a href="@Url.Action("Index","Deposit",new { page = (Model.Form.Page + 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Next</a>
        </div>
    </div>
}
else
{
    <p class="alert alert-info alert-dismissible fade show">You have not made deposits yet.</p>
}

Banktive.Web/Views/Deposit/SelectWallet.cshtml
@model Banktive.Web.Models.DepositModel.SelectWalletViewModel
@{
    ViewData["Title"] = "Select the wallet for deposits";
}

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />


<div class="row">
    @if (Model.Wallets.Any())
    {
        foreach (var address in Model.Wallets)
        {
            <section class="col-4 col-12-narrower">
                <header>
                    <h3>@Html.ActionLink(address.Name, "CreateTimeDeposit", "Deposit", new { id = address.Id }, new { @class = "loadingButton" })</h3>
                </header>
                <p>
                    Balance:
                    <strong><span class="balanceCBDCXRPLWallet" data-walletid="@address.Id">-</span> @address.Currency.Name</strong>
                    <br />
                    Alias : <strong>@address.Alias</strong> <br />
                    Description : <strong>@address.Description</strong> <br />
                    Id : <strong>@address.Id</strong> <br />
                </p>
                <ul class="actions">
                    <li><a href="@Url.Action("CreateTimeDeposit","Deposit", new { id = address.Id })" class="btn btn-info loadingButton">Select</a></li>
                </ul>
            </section>
        }
    }
    else
    {
        <div class="col-12">
            <p class="alert alert-info alert-dismissible">You do not have registered wallets</p>
        </div>
    }


</div>

Banktive.Web/Views/Deposit/ViewTimeDeposit.cshtml
@model Banktive.Web.Models.DepositModel.ViewTimeDepositViewModel
@{
    ViewData["Title"] = "Deposit details";
}

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />


<div class="row">
    <div class="col-md-6">

        <h3>Destination</h3>
        Address: @Model.Deposit.XRPLDestinationWallet

        @if (Model.Deposit.Destination != null)
        {
            <p>
                Name : @Model.Deposit.Destination.Name<br />
                Email: @Model.Deposit.Destination.Email<br />
                Account (name/id): @Model.Deposit.Destination.Account<br />
            </p>
        }

        @if (Model.Deposit.DepositStatusId == Constants.EscrowCancelled)
        {
            <div class="alert alert-warning" role="alert">
                This deposit was canceled by the creator. <br />
            </div>
        }
        else
        {
            if (Model.Deposit.DepositStatusId == Constants.EscrowConfirmed)
            {
                    
                <div class="alert alert-primary" role="alert">
                    This deposit was confirmed by the creator and you need to wait for the date to cash the money..<br />
                </div>
            }
            else
            {
                if (Model.Deposit.DepositStatusId == Constants.EscrowCreated)
                {
                    <div class="alert alert-info" role="alert">
                        Deposit is pending approval by the creator.<br />
                    </div>

                }
                else
                {
                    if (Model.Deposit.DepositStatusId == Constants.EscrowCashed)
                    {
                        <div class="alert alert-success" role="alert">
                            The deposit was approved and the money cashed by the destination. <br />
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-success" role="alert">
                            The deposit was rejected/expired by the creator. <br />
                        </div>
                        
                    }
                    
                }               
            }
         }

        


    </div>
    <div class="col-md-6">
        <h3>Payment data</h3>
        Wallet: @Model.Deposit.Wallet.Name <br />
        Amount: @Model.Deposit.Amount <br />
        Currency: @Model.Deposit.Currency.Name (@Model.Deposit.Currency.Code) <br />
        Date to cash: <span>@Model.Deposit.DateToCash.Value.ToLocalTime()</span> <br />
        Creation date: <span>@Model.Deposit.CreatedAt.ToLocalTime()</span> <br />
        Comments: @Model.Deposit.Comments <br />
    </div>

</div>
<br />
@if(Model.Deposit.DepositStatusId == Constants.EscrowConfirmed && Model.Deposit.DateToCash.Value.Date <= DateTime.Today.Date && Model.WalletForCash.UserId == User.Identity.Name)
{
    @using(Html.BeginForm("CashTimeDeposit","Deposit",FormMethod.Post,new {}))
    {
        <div class="row">
                    
            <div class="col-6">
                From: @Model.Deposit.UserId <br />
                <input type="hidden" name="successfulPayment" id="successfulPayment"/>
                <input type="hidden" value="@Model.Deposit.Id" name="id" id="id" />
                <input type="hidden" value="@Model.WalletForCash.Id" name="idWalletToCash" id="idWalletToCash" />
            </div>
            <div class="col-6">
                <input type="submit" value="Cash money" id="redeemMoney" class="btn btn-success" /> <br />
            </div>
        </div>
        <br />
    }
        
}

<br />
@if(Model.Deposit.DepositStatusId == Constants.EscrowConfirmed && Model.Deposit.DateToCash.Value.Date <= DateTime.Today.Date && Model.WalletForCash.UserId != User.Identity.Name)
{
    @using(Html.BeginForm("CancelTimeDeposit","Deposit",FormMethod.Post,new {}))
    {
        <div class="row">
                    
            <div class="col-6">
                From: @Model.Deposit.UserId <br />
                <input type="hidden" name="successfulPayment" id="successfulPayment"/>
                <input type="hidden" value="@Model.Deposit.Id" name="id" id="id" />
            </div>
            <div class="col-6">
                <input type="submit" value="Cancel deposit" id="redeemMoney" class="btn btn-danger" /> <br />
            </div>
        </div>
        <br />
    }
        
}