Banktive.Web/Models/ServiceModel/CheckSubscriptionViewModel.cs
using Banktive.Web.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Models.ServiceModel
{
    public class CheckSubscriptionViewModel
    {
        public Subscription Subscription { get;set; }
        public CheckSubscriptionFormModel Form { get; set; }
        public IEnumerable<SelectListItem> Wallets { get;set;}
        public ServiceAccountDetail PendingAccount { get;set; }


        public CheckSubscriptionViewModel(ApplicationDbContext db, Guid id, string userName)
        {
            Subscription = db.Subscriptions.SingleOrDefault(s => s.Id == id);
            Form = new CheckSubscriptionFormModel { SubscriptionId = id };
            Wallets = db.Wallets.Where(x => x.UserId == userName)
                .OrderBy(x => x.Name).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            PendingAccount = db.ServiceAccountDetails.Include(x => x.Currency).Include(x => x.ServiceAccount)
                .ThenInclude(x => x.Service).ThenInclude(x => x.Wallet).Where(x => x.ServiceAccount.ServiceId == Subscription.ServiceId && x.ServiceAccount.CustomerId == Subscription.CustomerId 
                && x.ServiceAccount.Service.ServiceTypeId == Subscription.ServiceTypeId && x.DueDate >= DateTime.UtcNow && x.Paid == false)
                .OrderBy(x=> x.DueDate).FirstOrDefault();
        }

        

    }
}

Banktive.Web/Controllers/ServiceController.cs
using Banktive.Web.Data;
using Banktive.Web.Models;
using Banktive.Web.Models.ServiceModel;
using Banktive.Web.Services;
using Banktive.Web.Services.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class ServiceController : Controller
    {
        private ApplicationDbContext _db;
        private XRPLService _XRPLService;

        public ServiceController(ApplicationDbContext db, XRPLService xrplService)
        {
            _db = db;
            _XRPLService = xrplService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Registered()
        {
            MyRegisteredViewModel model = new MyRegisteredViewModel(_db, User.Identity.Name);
            return View(model);
        }

        public IActionResult Register()
        {
            RegisterServiceViewModel model = new RegisterServiceViewModel(_db, User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public IActionResult Register(RegisterServiceFormModel Form)
        {
            if(!ModelState.IsValid)
            {
                RegisterServiceViewModel model = new RegisterServiceViewModel(_db, User.Identity.Name);
                model.Form = Form;
                return View(model);
            }

            Service service = new Service()
            {
                Name = Form.Name,
                CreatedAt = DateTime.UtcNow,
                UserId = User.Identity.Name,
                WalletId = Form.WalletId.Value, ServiceTypeId = Form.ServiceTypeId.Value
            };
            _db.Services.Add(service);
            _db.SaveChanges();
            return RedirectToAction("ServiceDetail", new { id = service.Id });
        }

        public IActionResult ServiceDetail(long id)
        {
            MyServiceViewModel model = new MyServiceViewModel(_db, id);
            if (model.Service == null || model.Service.UserId != User.Identity.Name)
            {
                return RedirectToAction("Registered");
            }
            return View(model);
        }

        public IActionResult ServiceAccounts(long id)
        {
            ServiceAccountsViewModel model = new ServiceAccountsViewModel(_db, id);
            if (model.Service == null || model.Service.UserId != User.Identity.Name)
            {
                return RedirectToAction("Registered");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult ServiceAccounts(ServiceAccountsFormModel Form)
        {
            ServiceAccountsViewModel model = new ServiceAccountsViewModel(_db, Form.Id);
            if(!string.IsNullOrEmpty(Form.CustomerId))
            {
                bool exists = _db.ServiceAccounts.Any(x => x.ServiceId == Form.Id && x.CustomerId == Form.CustomerId);
                if(exists)
                {
                    ModelState.AddModelError("Form.CustomerId", "This account already exists.");
                }
            }
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }
            ServiceAccount serviceAccount = new ServiceAccount
            {
                 CustomerId = Form.CustomerId, CreatedAt = DateTime.UtcNow, ServiceId = Form.Id
            };
            _db.ServiceAccounts.Add(serviceAccount);
            _db.SaveChanges();
            return RedirectToAction("ServiceAccounts", new { id = Form.Id });
        }

        public IActionResult ServiceAccountInfo(long id)
        {
            ServiceAccountInfoViewModel model = new ServiceAccountInfoViewModel(_db, id);
            return View(model);
        }

        [HttpPost]
        public IActionResult ServiceAccountInfo(ServiceAccountInfoFormModel Form)
        {
            ServiceAccountInfoViewModel model = new ServiceAccountInfoViewModel(_db, Form.ServiceAccountId);
            if(Form.DueDate.HasValue && Form.DueDate.Value.Date < DateTime.UtcNow.Date)
            {
                ModelState.AddModelError("Form.DueDate", "The date must be today or later.");
            }
            if(!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }
            ServiceAccountDetail detail = new ServiceAccountDetail
            {
                 ServiceAccountId = Form.ServiceAccountId, Amount = Form.Amount.Value, CreatedAt = DateTime.UtcNow,
                 CurrencyId = Constants.Currency_XRP, DueDate = Form.DueDate.Value, Id = Guid.NewGuid(), Paid = false
            };
            _db.ServiceAccountDetails.Add(detail);
            _db.SaveChanges();
            return RedirectToAction("ServiceAccountInfo", new { id = Form.ServiceAccountId });
        }


        public IActionResult Subscriptions()
        {
            MySubscriptionsViewModel model = new MySubscriptionsViewModel(_db, User.Identity.Name);
            return View(model);
        }

        public IActionResult Subscribe()
        {
            SubscribeServiceViewModel model = new SubscribeServiceViewModel(_db, User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public IActionResult Subscribe(SubscribeServiceFormModel Form)
        {
            SubscribeServiceViewModel model = new SubscribeServiceViewModel(_db, User.Identity.Name);
            if(Form.ServiceTypeId.HasValue && Form.CustomerId != null && Form.ServiceId.HasValue)
            {
                bool existService = _db.ServiceAccounts.Include(x => x.Service).Any(x => x.Service.ServiceTypeId == Form.ServiceTypeId && x.CustomerId == Form.CustomerId && x.ServiceId == Form.ServiceId);
                if(!existService)
                {
                    ModelState.AddModelError("Form.CustomerId", "There is no registered account for this customer and service.");
                }
            }
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }
            
            Subscription subscription = new Subscription
            {
                 CreatedAt = DateTime.UtcNow, CustomerId = Form.CustomerId, Id = Guid.NewGuid(),
                 ServiceId = Form.ServiceId.Value, ServiceName = Form.ServiceName, ServiceTypeId = Form.ServiceTypeId.Value,
                 UserId = User.Identity.Name
            };
            _db.Subscriptions.Add(subscription);
            _db.SaveChanges();

            return RedirectToAction("Subscriptions");
        }

        public IActionResult CheckSubscription(Guid id)
        {
            CheckSubscriptionViewModel model = new CheckSubscriptionViewModel(_db, id, User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CheckSubscription(CheckSubscriptionFormModel Form)
        {
            CheckSubscriptionViewModel model = new CheckSubscriptionViewModel(_db, Form.SubscriptionId, User.Identity.Name);
            if (!ModelState.IsValid)
            {
                
                model.Form = Form;
                return View(model);
            }

            Wallet walletForPayment = _db.Wallets.SingleOrDefault(x => x.Id == Form.WalletId.Value);
            string xrplAddress = model.PendingAccount.ServiceAccount.Service.Wallet.XRPLAddress;
            string serviceName = model.PendingAccount.ServiceAccount.Service.Name;
            Payment payment = new Payment
            {
                Amount = model.PendingAccount.Amount,
                PaymentStatusId = Constants.PaymentCreated,
                PaymentTypeId = Constants.ServicePayment,
                CreatedAt = DateTime.UtcNow,
                CurrencyId = Constants.Currency_XRP,
                //DestinationId = model.PendingAccount.ServiceAccount.Service.Wallet.XRPLAddress,
                XRPLDestinationWallet = xrplAddress,
                Id = Guid.NewGuid(),
                OriginWalletId = Form.WalletId.Value,
                UserId = User.Identity.Name,
                Comments = "Service payment for "+ serviceName
            };


            NativePaymentResult resultPayment = await _XRPLService.CreatePayment("wss://s.altnet.rippletest.net:51233", payment.XRPLDestinationWallet, payment.Amount,
                walletForPayment.XRPLAddress, walletForPayment.XRPLSeed);
            if (resultPayment.Successful)
            {
                payment.PaymentStatusId = Constants.PaymentConfirmed;
                payment.Fee = resultPayment.FeeAmount;
                model.PendingAccount.Paid = true;
            }
            else
            {
                payment.PaymentStatusId = Constants.PaymentRejected;
            }
            payment.ConfirmationAt = DateTime.UtcNow;
            _db.Payments.Add(payment);
            _db.SaveChanges();

            return RedirectToAction("CheckSubscription", new { id = Form.SubscriptionId });
        }
    }
}

Banktive.Web/Controllers/TransferController.cs
using Banktive.Web.Data;
using Banktive.Web.Models;
using Banktive.Web.Models.TransferModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class TransferController : Controller
    {
        private ApplicationDbContext _db;

        public TransferController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(long? wallet, int? month, int? year, int page = 1, int qty = 20)
        {
            IndexTransferViewModel model = new IndexTransferViewModel(_db, User.Identity.Name);
            IEnumerable<TransferDTO> payments = _db.Payments.Include(x => x.Wallet).Include(x => x.Currency).Where(x => x.UserId == User.Identity.Name && (x.PaymentStatusId == Constants.PaymentConfirmed))
                .Select(x => new TransferDTO
                {
                    Amount = x.Amount,
                    AssetCode = x.Currency.Code,
                    Comments = x.Comments,
                    CreatedAt = x.CreatedAt,
                    DestinationAddress = x.Destination != null? x.Destination.Account : x.XRPLDestinationWallet,
                    Id = x.Id,
                    Wallet = x.Wallet.Name,
                    WalletId = x.OriginWalletId, OriginAddress = x.Wallet.Alias,
                    IsSend = true
                });
            var myWalletAddresses = _db.Wallets.Where(x => x.UserId == User.Identity.Name).Select(x => x.XRPLAddress);
            var filterTransferForWallets = _db.Payments.Where(x => myWalletAddresses.Any(y => y == x.XRPLDestinationWallet) && x.PaymentStatusId == Constants.PaymentConfirmed).Select(x => new TransferDTO
            {
                Amount = x.Amount,
                AssetCode = x.Currency.Code,
                Comments = x.Comments,
                CreatedAt = x.CreatedAt,
                DestinationAddress = x.Destination != null ? x.Destination.Account : x.XRPLDestinationWallet,
                Id = x.Id,
                Wallet = x.Wallet.Name,
                WalletId = x.OriginWalletId,
                OriginAddress = x.Wallet.Alias,
                IsSend = false
            });
            payments = payments.Concat(filterTransferForWallets);
            if (wallet.HasValue)
            {
                payments = payments.Where(x => x.WalletId == wallet.Value);
            }
            if (month.HasValue)
            {
                payments = payments.Where(x => x.CreatedAt.Month == month.Value);
            }
            if (year.HasValue)
            {
                payments = payments.Where(x => x.CreatedAt.Year == year.Value);
            }
            model.Payments = payments.OrderByDescending(x => x.CreatedAt).Skip(qty * (page - 1)).Take(qty);
            model.Form.Page = page;
            model.Form.Year = year;
            model.Form.Month = month;
            model.Form.WalletId = wallet;
            return View(model);
        }


        public IActionResult Detail(Guid id)
        {
            DetailTransferViewModel model = new DetailTransferViewModel(_db, id);
            return View(model);
        }
    }
}

Banktive.Web/Controllers/WalletController.cs
using Banktive.Web.Data;
using Banktive.Web.Models.WalletModel;
using Banktive.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class WalletController : Controller
    {
        private ApplicationDbContext _db;
        private XRPLService _XRPLService;

        public WalletController(ApplicationDbContext db, XRPLService xrplService)
        {
            _db = db;
            _XRPLService = xrplService;
        }

        public IActionResult Index()
        {
            IndexWalletViewModel model = new IndexWalletViewModel(_db, User.Identity.Name);
            if(model.Profile == null)
            {
                return RedirectToAction("Index", "Setting");
            }
            return View(model);
        }

        public IActionResult Create()
        {
            CreateWalletViewModel model = new CreateWalletViewModel(_db);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateWalletFormModel Form)
        {
            CreateWalletViewModel model = new CreateWalletViewModel(_db);
            if (!string.IsNullOrWhiteSpace(Form.Alias))
            {
                string alias = Form.Alias.ToLower();
                bool existAlias = _db.Wallets.Any(x => x.Alias == alias);
                if (existAlias)
                {
                    ModelState.AddModelError("Form.Alias", "The alias is already occupied by another account");
                }
            }
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }

            Wallet wallet = new Wallet
            {
                 Alias = Form.Alias, CreatedAt = DateTime.UtcNow, CurrencyId = Form.CurrencyId.Value,
                 XRPLAddress = Form.XRPLAddress, Description = Form.Description, Name = Form.Name,
                 XRPLSeed = Form.XRPLSeed, UserId = User.Identity.Name
            };
            _db.Wallets.Add(wallet);
            _db.SaveChanges();
            return RedirectToAction("View", new { id = wallet.Id });
        }

        public IActionResult View(long id)
        {
            ViewWalletViewModel model = new ViewWalletViewModel(_db, id);
            if(model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Update(long id)
        {
            UpdateWalletViewModel model = new UpdateWalletViewModel(_db, id);
            if (model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(UpdateWalletFormModel Form)
        {
            UpdateWalletViewModel model = new UpdateWalletViewModel(_db, Form.Id);
            if (model.Wallet == null || model.Wallet.UserId != User.Identity.Name)
            {
                model.Form = Form;
                return View(model);
            }
            Wallet wallet = _db.Wallets.SingleOrDefault(x => x.Id == Form.Id);
            wallet.Name = Form.Name;
            wallet.Description = Form.Description;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetNativeBalance(long id)
        {
            Wallet wallet = _db.Wallets.SingleOrDefault(x => x.Id == id);
            if (wallet== null || wallet.UserId != User.Identity.Name)
            {
                return Json(null);
            }
            var nativeBalance = await _XRPLService.GetNativeBalance("wss://s.altnet.rippletest.net:51233", wallet.XRPLAddress);
            if (nativeBalance == null)
            {
                return Json(null);
            }
            return Json(nativeBalance);
        }
    }
}

Banktive.Web/Views/Service/CheckSubscription.cshtml
@model Banktive.Web.Models.ServiceModel.CheckSubscriptionViewModel
@{
    ViewData["Title"] = "Check pending charges";
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-12">
        @Html.ActionLink("Back", "Subscriptions","Service", null, new { @class="btn btn-info" })
    </div>
</div>
<br />

@if(Model.PendingAccount != null)
{

    <div class="row">
        <div class="col-12">
            <h4>Pending charge</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            Final date to pay: <b>@Model.PendingAccount.DueDate.ToLocalTime()</b>
        </div>
        <div class="col-3">
            Amount: @Model.PendingAccount.Amount (@Model.PendingAccount.Currency.Name)
        </div>
    </div>

    @using(Html.BeginForm())
    {
        @Html.HiddenFor(x => x.Form.SubscriptionId)
        <div class="row">
            <div class="col-3">
                @Html.LabelFor(x => x.Form.WalletId)
            </div>
            <div class="col-6">
                @Html.DropDownListFor(x => x.Form.WalletId, Model.Wallets,"Select a wallet",new {@class="form-control"}) <br />
                @Html.ValidationMessageFor(x => x.Form.WalletId)
            </div>
            <div class="col-3">
                <div class="alert alert-info">
                    Select your wallet to make this payment
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-3">
                <br />
            </div>
            <div class="col-6">
                <input type="submit" value="Pay account" class="btn btn-success" />
            </div>
        </div>
        <br />
    }
}
else
{
    <p class="alert alert-success alert-dismissible fade show">You have no pending charges that you must pay.</p>
}

Banktive.Web/Views/Service/Index.cshtml
@{
    ViewData["Title"] = "Services";
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>Services</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />



<div class="row">
    <div class="col-6">
        <h4>Subscribed services</h4>
        <p class="alert alert-info alert-dismissible">
            Manage and pay the bills for the services to which you are subscribed. <br />
            @Html.ActionLink("My subscriptions","Subscriptions","Service",null,new {@class="btn btn-success"})
        </p>
    </div>
    <div class="col-6">
        <h4>My services</h4>
        <p class="alert alert-primary alert-dismissible">
            Manage your own services to charge from your subscribers/customers. <br />
            @Html.ActionLink("My services","Registered","Service",null,new {@class="btn btn-success"})
        </p>
    </div>


</div>

Banktive.Web/Views/Service/Register.cshtml
@model Banktive.Web.Models.ServiceModel.RegisterServiceViewModel
@{
    ViewData["Title"] = "Register new service";
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-12">
        @Html.ActionLink("Back", "Index","Service", null, new { @class="btn btn-info" })
    </div>
</div>
<br />

@using(Html.BeginForm())
{
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Name)
        </div>
        <div class="col-6">
            @Html.TextBoxFor(x => x.Form.Name, new { placeholder="My service", @class="form-control"}) <br />
            @Html.ValidationMessageFor(x => x.Form.Name)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the name for your new service for payments and transactions.
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.ServiceTypeId)
        </div>
        <div class="col-6">
            @Html.DropDownListFor(x => x.Form.ServiceTypeId, Model.ServiceTypes,"Select a service type",new {@class="form-control"}) <br />
            @Html.ValidationMessageFor(x => x.Form.ServiceTypeId)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the service type (category).
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.WalletId)
        </div>
        <div class="col-6">
            @Html.DropDownListFor(x => x.Form.WalletId, Model.Wallets,"Select a wallet",new {@class="form-control"}) <br />
            @Html.ValidationMessageFor(x => x.Form.WalletId)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Select your wallet to receive payments
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            <br />
        </div>
        <div class="col-6">
            <input type="submit" value="Register" class="btn btn-success" />
        </div>
    </div>
    <br />
}

Banktive.Web/Views/Service/Registered.cshtml
@model Banktive.Web.Models.ServiceModel.MyRegisteredViewModel
@{
    ViewData["Title"] = "My own services";
}

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        @Html.ActionLink("Register new service", "Register","Service",null,new {@class="btn btn-info"})
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />

<table class="table table-responsive table-hover">
        <thead>
            <tr>
                <th>Date</th>
                <th>Name</th>
                <th>Service Type</th>
                <th>Wallet (to receive payments)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var payment in Model.Services)
            {
                <tr>
                    <td>@payment.CreatedAt.ToLocalTime()</td>
                    <td>@payment.Name</td>
                    <td>@payment.ServiceType.Name</td>
                    <td>
                        @payment.Wallet.Name
                    </td>
                    <td>@Html.ActionLink("Details", "ServiceDetail", "Service", new { id = payment.Id }, new { @class = "btn btn-success loadingButton" })
                        @Html.ActionLink("Accounts", "ServiceAccounts", "Service", new { id = payment.Id }, new { @class = "btn btn-primary loadingButton" })
                    </td>
                </tr>
            }
        </tbody>
    </table>

Banktive.Web/Views/Service/ServiceAccounts.cshtml
@model Banktive.Web.Models.ServiceModel.ServiceAccountsViewModel
@{
    ViewData["Title"] = "Accounts for "+Model.Service.Name;
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />


<div class="row">
    <div class="col-12">
        <h3>Add new account</h3>
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(x => x.Form.Id)
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(x => x.Form.CustomerId) 
                    @Html.TextBoxFor(x => x.Form.CustomerId, new { @class = "form-control" }) <br />
                    @Html.ValidationMessageFor(x => x.Form.CustomerId) 
                </div>
                <div class="col-md-6">
                    <input type="submit" value="Add new account" class="btn btn-secondary loadingButton" />
                </div>
            </div>
        }
    </div>
            

    </div>
<br /><br />
<div class="row">
    <div class="col-12">
        <h3>Accounts for this service</h3>
@if (Model.ServiceAccounts.Any())
{
    @*<div class="row">
        <div class="col-6 text-right">
            @if (Model.Page > 1)
            {
                <a href="@Url.Action("Index","Transfer",new { page = (Model.Form.Page - 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Previous</a>
            }
        </div>
        <div class="col-6 text-left">
            <a href="@Url.Action("Index","Transfer",new { page = (Model.Form.Page + 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Next</a>
        </div>
    </div>*@
    <table class="table table-responsive">
        <thead>
            <tr>
                <th>Date</th>
                <th>Customer Id</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.ServiceAccounts)
            {
                <tr>
                    <td>@account.CreatedAt.ToLocalTime()</td>
                    <td>@account.CustomerId</td>
                    <td>@Html.ActionLink("Details", "ServiceAccountInfo", "Service", new { id = account.Id }, new { @class = "btn btn-success loadingButton" })</td>
                </tr>
            }
        </tbody>
    </table>
    @*<div class="row">
        <div class="col-6 text-right">
            @if (Model.Page > 1)
            {
                <a href="@Url.Action("Index","Transfer",new { page = (Model.Form.Page - 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Previous</a>
            }
        </div>
        <div class="col-6 text-left">
            <a href="@Url.Action("Index","Transfer",new { page = (Model.Form.Page + 1), wallet = Model.Form.WalletId, year= Model.Form.Year, month = Model.Form.Month })">Next</a>
        </div>
    </div>*@
}
else
{
    <p class="alert alert-info alert-dismissible fade show">You do not have any account registered for this service.</p>
}
</div>
            

    </div>

Banktive.Web/Views/Service/ServiceDetail.cshtml
@model Banktive.Web.Models.ServiceModel.MyServiceViewModel
@{
    ViewData["Title"] = "Service details";
}

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />


<div class="row">
    <div class="col-md-6">

        <h3>Details</h3>
        Id: @Model.Service.Id <br />
        Name: @Model.Service.Name <br />
        Type: @Model.Service.ServiceType.Name <br />
        Created at: @Model.Service.CreatedAt.ToLocalTime() <br />
        Wallet (to receive money): <a href="@Url.Action("View","Wallet",new {id = Model.Service.WalletId})" target="_blank">@Model.Service.Wallet.Name</a><br />
    </div>
    <div class="col-md-6">
        <h3>Accounts</h3>
        Manage the accounts of your clients/subscribers to receive money in this service. <br />
        @Html.ActionLink("Accounts","ServiceAccounts","Service",new {id = Model.Service.Id }, new {@class="btn btn-secondary"})
    </div>

</div>

Banktive.Web/Views/Service/Subscriptions.cshtml
@model Banktive.Web.Models.ServiceModel.MySubscriptionsViewModel
@{
    ViewData["Title"] = "My subscriptions";
}



<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />

<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        @Html.ActionLink("Subscribe service", "Subscribe","Service",null,new {@class="btn btn-info"})
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />

<table class="table table-responsive table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Customer Id</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var payment in Model.Subscriptions)
        {
            <tr>
                <td>@payment.ServiceName</td>
                <td>@payment.ServiceType.Name</td>
                <td>@payment.CustomerId</td>
                <td>@Html.ActionLink("Check pending charges", "CheckSubscription", "Service", new { id = payment.Id }, new { @class = "btn btn-success loadingButton" })
                </td>
            </tr>
        }
    </tbody>
</table>