Banktive.Web/Controllers/DestinationController.cs
using Banktive.Web.Data;
using Banktive.Web.Models.DestinationModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Banktive.Web.Controllers
{
    [Authorize]
    public class DestinationController : Controller
    {
        private ApplicationDbContext _db;

        public DestinationController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(IndexDestinationFormModel Form)
        {
            IndexDestinationViewModel model = new IndexDestinationViewModel(_db, User.Identity.Name);
            if(!string.IsNullOrWhiteSpace(Form.Name))
            {
                model.Destinations = model.Destinations.Where(x => x.Name.Contains(Form.Name));
            }
            if (!string.IsNullOrWhiteSpace(Form.Email))
            {
                model.Destinations = model.Destinations.Where(x => x.Email.Contains(Form.Email));
            }
            if (!string.IsNullOrWhiteSpace(Form.Account))
            {
                model.Destinations = model.Destinations.Where(x => x.Account.Contains(Form.Account));
            }
            model.Form = Form;
            return View(model);
        }

        public IActionResult Add()
        {
            AddDestinationViewModel model = new AddDestinationViewModel(_db, User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddDestinationFormModel Form)
        {
            if(Form.Account!= null)
            {
                var exists = _db.Destinations.Any(x => x.UserId == User.Identity.Name && x.Account == Form.Account);
                if(exists)
                {
                    ModelState.AddModelError("Form.Account", "This account was already added.");
                }
            }
            if(!ModelState.IsValid)
            {
                AddDestinationViewModel model = new AddDestinationViewModel(_db, User.Identity.Name);
                model.Form = Form;
                return View(model);
            }

            Destination destination = new Destination
            {
                 Account = Form.Account, CreatedAt = DateTime.UtcNow, Email = Form.Email, Id = Guid.NewGuid(),
                 LastUpdatedAt = DateTime.UtcNow, Name = Form.Name, UserId = User.Identity.Name
            };
            _db.Destinations.Add(destination);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid id)
        {
            EditDestinationViewModel model = new EditDestinationViewModel(_db, id);
            if(model.Destination == null || model.Destination.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditDestinationFormModel Form)
        {
            EditDestinationViewModel model = new EditDestinationViewModel(_db, Form.Id);
            if (model.Destination == null || model.Destination.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            if (!ModelState.IsValid)
            {
                model.Form = Form;
                return View(model);
            }
            Destination destination = _db.Destinations.SingleOrDefault(x => x.Id == Form.Id);
            destination.Name = Form.Name;
            destination.LastUpdatedAt = DateTime.UtcNow;
            destination.Email = Form.Email;
            //destination.Account = Form.Account;

            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            Destination destination = _db.Destinations.SingleOrDefault(x => x.Id == id);
            if(destination == null || destination.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            _db.Destinations.Remove(destination);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Detail(Guid id)
        {
            DetailDestinationViewModel model = new DetailDestinationViewModel(_db, id);
            if (model.Destination == null || model.Destination.UserId != User.Identity.Name)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Banktive.Web/Views/Destination/Add.cshtml
@model Banktive.Web.Models.DestinationModel.AddDestinationViewModel
@{
    ViewData["Title"] = "Add new destination";
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-12">
        @Html.ActionLink("Back", "Index","Destination", null, new { @class="btn btn-info" })
    </div>
</div>
<br />

@using(Html.BeginForm())
{
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Name)
        </div>
        <div class="col-6">
            @Html.TextBoxFor(x => x.Form.Name, new { placeholder="My customer"}) <br />
            @Html.ValidationMessageFor(x => x.Form.Name)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the name for your new destination for payments and transactions.
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Account)
        </div>
        <div class="col-6">
            @Html.TextBoxFor(x => x.Form.Account, new { placeholder="12784534 or rSDgd.... or username"}) <br />
            @Html.ValidationMessageFor(x => x.Form.Account)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the number or name of the account of your destination in Banktive, or you can enter an address in the XRPL network.
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Email)
        </div>
        <div class="col-6">
            @Html.TextBoxFor(x => x.Form.Email, new { placeholder="test@test.com", type="email"}) <br />
            @Html.ValidationMessageFor(x => x.Form.Email)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the email for your destination.
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            <br />
        </div>
        <div class="col-6">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
    <br />
}

Banktive.Web/Views/Destination/Detail.cshtml
@model Banktive.Web.Models.DestinationModel.DetailDestinationViewModel
@{
    ViewData["Title"] = "Details of " + Model.Destination.Name;
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-4">
        @Html.ActionLink("Back", "Index","Destination", null, new { @class="btn btn-info" })
    </div>
    <div class="col-4">
        @Html.ActionLink("Update/delete", "Edit","Destination", new {id = Model.Destination.Id}, new { @class="btn btn-info" })
    </div>
</div>
<br />


<div class="row">
    <div class="col-3">
        Name
    </div>
    <div class="col-6">
        <b>@Model.Destination.Name</b>
    </div>
</div>
<br />
<div class="row">
    <div class="col-3">
        Account
    </div>
    <div class="col-6">
        <b>@Model.Destination.Account</b>
    </div>
</div>
<br />
<div class="row">
    <div class="col-3">
        Email
    </div>
    <div class="col-6">
        <b>@Model.Destination.Email</b>
    </div>
</div>
<br />
<div class="row">
    <div class="col-3">
        Created at
    </div>
    <div class="col-6">
        <b>@Model.Destination.CreatedAt</b>
    </div>
</div>
<br />
<div class="row">
    <div class="col-3">
        Last updated at
    </div>
    <div class="col-6">
        <b>@Model.Destination.LastUpdatedAt</b>
    </div>
</div>
<br />

<div class="row">
    <div class="col-4">
        @Html.ActionLink("Back", "Index","Destination", null, new { @class="btn btn-info" })
    </div>
    <div class="col-4">
        @Html.ActionLink("Update/delete", "Edit","Destination", new {id = Model.Destination.Id}, new { @class="btn btn-info" })
    </div>
</div>
<br />

Banktive.Web/Views/Destination/Edit.cshtml
@model Banktive.Web.Models.DestinationModel.EditDestinationViewModel
@{
    ViewData["Title"] = "Update " + Model.Destination.Name;
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-12">
        @Html.ActionLink("Back", "Index","Destination", null, new { @class="btn btn-info" })
    </div>
</div>
<br />

@using(Html.BeginForm())
{
    @Html.HiddenFor(x => x.Form.Id)

    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Name)
        </div>
        <div class="col-6">
            @Html.TextBoxFor(x => x.Form.Name, new { placeholder="My customer"}) <br />
            @Html.ValidationMessageFor(x => x.Form.Name)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the name for your new destination for payments and transactions.
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            Account
        </div>
        <div class="col-6">
            <b>@Model.Destination.Account</b>
        </div>
        
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Email)
        </div>
        <div class="col-6">
            @Html.TextBoxFor(x => x.Form.Email, new { placeholder="test@test.com", type="email"}) <br />
            @Html.ValidationMessageFor(x => x.Form.Email)
        </div>
        <div class="col-3">
            <div class="alert alert-info">
                Enter the email for your destination.
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-3">
            <br />
        </div>
        <div class="col-6">
            <input type="submit" value="Update" class="btn btn-success" />
        </div>
    </div>
    <br />
}

@if(!Model.ExistPayments)
{
    <br /><br />
    <div class="row">
        @using(Html.BeginForm("Delete","Destination"))
        {
            <input type="hidden" value="@Model.Destination.Id" name="id" />
    
            <div class="col-3">
                <h4>Delete</h4>
            </div>
            <div class="col-6">
                <div class="alert alert-danger">
                    This action is irreversible. Transactions made to this destination are maintained and will not be affected.
                </div>
            </div>
            <div class="col-3">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        }
    </div>
    <br />
}

Banktive.Web/Views/Destination/Index.cshtml
@model Banktive.Web.Models.DestinationModel.IndexDestinationViewModel
@{
    ViewData["Title"] = "My Destinations";
}


<div class="row">
    <div class="col-3">
        <br/>
    </div>
    <div class="col-6">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-3">
        <br/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-12">
        @Html.ActionLink("Add new destination", "Add","Destination", null, new { @class="btn btn-info" })
    </div>
</div>
<br />
<div class="row">
    @using(Html.BeginForm(null,null, FormMethod.Get))
    {
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Name) <br/>
            @Html.TextBoxFor(x => x.Form.Name, new {@class="form-control"})
        </div>
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Email) <br/>
            @Html.TextBoxFor(x => x.Form.Email, new {@class="form-control"})
        </div>
        <div class="col-3">
            @Html.LabelFor(x => x.Form.Account) <br/>
            @Html.TextBoxFor(x => x.Form.Account, new {@class="form-control"})
        </div>
        <div class="col-3">
            <input type="submit" value="Filter" class="btn btn-primary" />
        </div>
    }
</div>
<br />
<div class="row">
    @if(Model.Destinations.Any())
    {
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Account</th>
                    <th>Email</th>
                    <th>Last updated at</th>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach(var destination in Model.Destinations)
                {
                    <tr>
                        <th>@destination.Name</th>
                        <td>@destination.Account</td>
                        <td>@destination.Email</td>
                        <td>@destination.LastUpdatedAt</td>
                        <td>
                            @Html.ActionLink("Details","Detail","Destination",new {id = destination.Id}, new {@class="btn btn-secondary"}) <br />
                            @Html.ActionLink("Update/Delete","Edit","Destination",new {id = destination.Id}, new {@class="btn btn-secondary"})
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="col-12">
            <div class="alert alert-info">
                You have no destinations.
            </div>
        </div>
    }
</div>
<br />